Remove runtime pin on ipywidgets
conda-forge/jupyter-rfb-feedstock pull request #7
Opened 2023-10-25 20:11 UTC by QuLogic

Because not all releases are pinned, the effect of this pin is to simply get the latest unpinned version, 0.3.1, which is _still broken_ with ipywidgets 8.

In any case, this version, 0.3.3, is supposed to have fixed compatibility with ipywidgets 8, https://github.com/vispy/jupyter_rfb/pull/64.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [n/a] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [n/a] Ensured the license file is being packaged.

2023-10-25 23:02 UTC, kushalkolar requested changes

2023-10-25 23:02 UTC, kushalkolar commented on recipe/meta.yaml
>      - python >=3.6
```suggestion
    - python >=3.9
```

Latest jupyter-rfb requires >=3.9

2023-10-25 23:02 UTC, kushalkolar commented on recipe/meta.yaml
> +    - ipywidgets >=7.6.0
```suggestion
    - ipywidgets >=7.6.0,<9.0.0
```

probably a good idea to pin below v9

2023-10-26 00:46 UTC, QuLogic commented on recipe/meta.yaml
>      - python >=3.6
Only for 0.4.1, which is #6.

2023-10-26 00:57 UTC, kushalkolar commented on recipe/meta.yaml
>      - python >=3.6
ah, I didn't notice this is the recipe for v0.3

2023-10-26 02:04 UTC, QuLogic commented on recipe/meta.yaml
> +    - ipywidgets >=7.6.0
I'm not sure how safe that is, because of the unpinned releases. If you do `conda create -p /tmp/rfb 'ipywidgets>=8' jupyter-rfb`, then it installs 0.3.1, even though that version combination is broken. Is there a way to block/replace 0.3.1 with a pin, so that this pin would be effective?

2023-10-26 02:16 UTC, kushalkolar commented on recipe/meta.yaml
> +    - ipywidgets >=7.6.0
are you basically trying to get this with ipywidgets v8? I'd wait for #6 , I'll take a look too if I can get access to retry the build

2023-10-26 02:20 UTC, QuLogic commented on recipe/meta.yaml
> +    - ipywidgets >=7.6.0
AFAICT, 0.3.3 should be okay with ipywidgets v8. And the failure in #6 would be fixed by the second commit here.

2023-11-29 09:17 UTC, kushalkolar commented
@QuLogic v0.4.x releases are now on conda-forge and incorporate those changes to the recipe, do you think we can close this? Thanks! :smile:

2023-12-01 04:45 UTC, QuLogic commented
Yes, it appears so.

2023-12-01 04:45 UTC, closed without merging